<a href="https://colab.research.google.com/github/Souptikbej/Pandas-Class/blob/main/Pandas_Class10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **What is Feature Engineering?**
Feature engineering means creating new, meaningful features (columns) from existing data to improve analysis or model performance.

In [28]:
import pandas as pd

df = pd.DataFrame({
    "Employee_ID": [101,102,103,104,105],
    "Name": ["Rahul Sharma","Priya Sen","Amit Ghosh","Neha Dhuly","Rohan Dhara"],
    "Age": [24,30,45,27,38],
    "Salary": [40000,75000,120000,55000,90000],
    "Sales": [120000,180000,250000,150000,210000],
    "Cost": [80000,120000,180000,100000,140000],
    "Experience": [2,5,15,4,10],
    "Join_Date": pd.to_datetime([
        "2022-01-10",
        "2020-05-15",
        "2015-08-20",
        "2021-03-01",
        "2018-11-12"
    ])
})
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12

## **Feature 1: Profit**
**Business Question**
> What profit did each employee generate?

In [29]:
df['Profit']=df['Sales']-df['Cost']
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000

## **Feature 2: Profit Margin %**
**Business Question**

>Which employee has the highest profit margin?

In [30]:
df['Profit_margin']=(df['Profit']/df['Sales'])*100
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333

## **Feature 3: Experience Level**
**Business Question**

>Categorize employees by experience.


```
0–2 years      → Beginner
3–7 years      → Intermediate
8+ years       → Expert
```

In [31]:
def exp(n):
  if n<=2:
    return 'Beginner'
  elif n<=7 and n>=3:
    return 'Intermediate'
  else:
    return 'Expert'
df['Experience_Level']=df['Experience'].apply(exp)
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert

## **Feature 4: Salary Band**
**Business Question**

>Group employees into salary bands.
```
< 50000      → Low
50000–90000  → Medium
> 90000      → High
```

In [32]:
def band(n):
  if n<50000:
    return 'Low'
  elif n<=90000 and n>=50000:
    return 'Medium'
  else:
    return 'High'
df['Salary_Band']=df['Salary'].apply(band)
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium

## **Feature 5: Employee Tenure**
**Business Question**

>How many days has each employee worked?

In [33]:
df['Tenure_Days'] = (pd.Timestamp.today() - df['Join_Date']).dt.days
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low,1631
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium,2236
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High,3966
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium,1946
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786

## **Feature 6: Employee Tenure (Years)**
**Business Question**

>How many years has each employee worked?

In [34]:
df['Tenure_Years'] = (df['Tenure_Days']/365).round(1)
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days,Tenure_Years
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low,1631,4.5
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium,2236,6.1
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High,3966,10.9
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium,1946,5.3
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786,7.6

## **Feature 7: Revenue per Year of Experience**
**Business Question**

>Which employee generates the most sales relative to experience?

In [35]:
df["Sales_Per_Year"] = (df["Sales"] / df["Experience"]).round()
df["Sales_Per_Year"] = df["Sales_Per_Year"].astype(int)
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days,Tenure_Years,Sales_Per_Year
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low,1631,4.5,60000
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium,2236,6.1,36000
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High,3966,10.9,16667
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium,1946,5.3,37500
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786,7.6,21000

## **Feature 8: High Performer**
**Business Question**

>Mark employees as High Performer if profit exceeds ₹60,000.

In [36]:
df["High_Performer"] = df["Profit"].apply(lambda x: "Yes" if x > 60000 else "No")
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days,Tenure_Years,Sales_Per_Year,High_Performer
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low,1631,4.5,60000,No
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium,2236,6.1,36000,No
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High,3966,10.9,16667,Yes
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium,1946,5.3,37500,No
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786,7.6,21000,Yes

## **Feature 9: Initials**
**Business Question**

>Generate employee initials.
```
Rahul Sharma
↓
RS
```

In [37]:
df["Initials"] = df["Name"].apply(lambda x: "".join(word[0] for word in x.split()))
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days,Tenure_Years,Sales_Per_Year,High_Performer,Initials
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low,1631,4.5,60000,No,RS
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium,2236,6.1,36000,No,PS
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High,3966,10.9,16667,Yes,AG
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium,1946,5.3,37500,No,ND
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786,7.6,21000,Yes,RD

## **Feature 10: Employee Email**
**Business Question**

>Create company email IDs.
```
Rahul
↓
rahul@company.com

```

In [38]:
df['Email']=df['Name'].apply(lambda x: x.lower().replace(" ","")+"@company.com")
df

,Employee_ID,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days,Tenure_Years,Sales_Per_Year,High_Performer,Initials,Email
0,101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low,1631,4.5,60000,No,RS,rahulsharma@company.com
1,102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium,2236,6.1,36000,No,PS,priyasen@company.com
2,103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High,3966,10.9,16667,Yes,AG,amitghosh@company.com
3,104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium,1946,5.3,37500,No,ND,nehadhuly@company.com
4,105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786,7.6,21000,Yes,RD,rohandhara@company.com

## **After Create these columns then answer:**

1. Who has the highest profit?
1. Which salary band has the most employees?
1. Average tenure?
1. Highest profit margin?
1. Number of high performers?

In [42]:
#Who has the highest profit?
df[df['Profit']==df['Profit'].max()].set_index('Employee_ID')

,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days,Tenure_Years,Sales_Per_Year,High_Performer,Initials,Email
Employee_ID,,,,,,,,,,,,,,,,,
103,Amit Ghosh,45,120000,250000,180000,15,2015-08-20,70000,28.000000,Expert,High,3966,10.9,16667,Yes,AG,amitghosh@company.com
105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786,7.6,21000,Yes,RD,rohandhara@company.com

In [43]:
#Which salary band has the most employees?
df['Salary_Band'].value_counts()

Salary_Band
Medium    3
Low       1
High      1
Name: count, dtype: int64

In [44]:
#Average tenure?
df['Tenure_Years'].mean()

np.float64(6.88)

In [45]:
#Highest profit margin?
df[df['Profit_margin']==df['Profit_margin'].max()].set_index('Employee_ID')

,Name,Age,Salary,Sales,Cost,Experience,Join_Date,Profit,Profit_margin,Experience_Level,Salary_Band,Tenure_Days,Tenure_Years,Sales_Per_Year,High_Performer,Initials,Email
Employee_ID,,,,,,,,,,,,,,,,,
101,Rahul Sharma,24,40000,120000,80000,2,2022-01-10,40000,33.333333,Beginner,Low,1631,4.5,60000,No,RS,rahulsharma@company.com
102,Priya Sen,30,75000,180000,120000,5,2020-05-15,60000,33.333333,Intermediate,Medium,2236,6.1,36000,No,PS,priyasen@company.com
104,Neha Dhuly,27,55000,150000,100000,4,2021-03-01,50000,33.333333,Intermediate,Medium,1946,5.3,37500,No,ND,nehadhuly@company.com
105,Rohan Dhara,38,90000,210000,140000,10,2018-11-12,70000,33.333333,Expert,Medium,2786,7.6,21000,Yes,RD,rohandhara@company.com

In [46]:
#Number of high performers?
df['High_Performer'].value_counts()

High_Performer
No     3
Yes    2
Name: count, dtype: int64